### ISSUE TITLE
DoaTests can randomly fail 

### ISSUE THREAD

**Issue by Xela101** [catalyst-network/Catalyst.Framework#1064]

**Comment by monsieurleberre** [comment]
This seems to be coming from the fact that DaoBase is relying on a static MasterMapper from MapperProvider, but MasterMapper only initialise this static field from an instance constructor.
It is not guaranteed that the instance constructor has been called before the static is accessed.

My opinion is that the DaoBase class is doing too much: it is a DAO object, so should be plain and simple, but it also implements IMapperInitialiser and IValueConverter.
Then we should rely on Autofac rather than static instances to implement singletons like this seems to be intended.
