### ISSUE TITLE
Bug with p2p and rpc message handlers.json

### ISSUE THREAD

**Issue by Xela101** [catalyst-network/Catalyst.Framework#1071]
In the POA Node. They seem to be conflicting, all handlers are not injected into the application at run-time causing some messages not to work.

**Comment by monsieurleberre** [comment]
OK last time I checked and fixed that it was because they were not being used correctly, when using multiple config files the last one used superseeds the first one, so if you want to split files, they need to both come in the main component file as JsonConfiguredModule
I will have a look and if it is something that came back by mistake will fix it :)

**Comment by monsieurleberre** [comment]
I ended up doing it in code and not using JSON modules as the trend seems to be getting rid of these kinds of files.

**Comment by monsieurleberre** [comment]
done
